version: '3.8'

services:
  rm-manager:
    build: .
    container_name: rm-manager
    ports:
      - "8501:8501"
    volumes:
      # Persiste la configuration et les données
      - ./data:/app/data
    restart: unless-stopped
